const ActionTypes = {
  GET_ARTIST_LIST: 'GET_ARTIST_LIST',
  ARTIST_LIST_SUCCESS: 'ARTIST_LIST_SUCCESS',
  ARTIST_LIST_FAIURE: 'ARTIST_LIST_FAIURE',
  GET_ARTIST_DETAILS: 'GET_ARTIST_DETAILS',
  ARTIST_DETAILS_SUCCESS: 'ARTIST_DETAILS_SUCCESS',
  ARTIST_DETAILS_FAILURE: 'ARTIST_DETAILS_FAILURE',

}

export default ActionTypes
