const ActionTypes = {
  GET_ARTIST_LIST: 'GET_ARTIST_LIST',
  ARTIST_LIST_SUCCESS: 'ARTIST_LIST_SUCCESS',
  ARTIST_LIST_FAIURE: 'ARTIST_LIST_FAIURE',
  GET_ARTIST_DETAILS: 'GET_ARTIST_DETAILS',
  ARTIST_DETAILS_SUCCESS: 'ARTIST_DETAILS_SUCCESS',
  ARTIST_DETAILS_FAILURE: 'ARTIST_DETAILS_FAILURE',
  GET_ALBUM_LIST: 'GET_ALBUM_LIST',
  ALBUM_LIST_SUCCESS: 'ALBUM_LIST_SUCCESS',
  ALBUM_LIST_FAIURE: 'ALBUM_LIST_FAIURE',
  GET_ALBUM_DETAILS: 'GET_ALBUM_DETAILS',
  ALBUM_DETAILS_SUCCESS: 'ALBUM_DETAILS_SUCCESS',
  ALBUM_DETAILS_FAILURE: 'ALBUM_DETAILS_FAILURE',

}

export default ActionTypes
